In [1]:
import requests
import json
import pandas as pd
import numpy as np

In [56]:
apiData = requests.get("https://api.covidtracking.com/v1/us/daily.json")

In [57]:
stringData = json.loads(apiData.text)

In [58]:
covid = pd.DataFrame(stringData)
covid.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,totalTestResults,lastModified,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,hash
0,20201108,56,9864069,127671847,23353.0,56768.0,494349.0,11108.0,25819.0,2959.0,...,156478414,2020-11-08T24:00:00Z,0,0,462,1576,778663,102588,1086653,56c1d4c47c86a9296962a1d88ccd594a307c234c
1,20201107,56,9761481,126893184,23295.0,55817.0,492773.0,11078.0,25721.0,2943.0,...,155391761,2020-11-07T24:00:00Z,0,0,1097,2304,974432,128396,1384557,c4f01e089557e1cbd0e84222456d324979ad5492
2,20201106,56,9633085,125918752,11804.0,54824.0,490469.0,11085.0,25498.0,2850.0,...,154007204,2020-11-06T24:00:00Z,0,0,1186,3054,1113428,125252,1533406,0e74a42e553238c2ec4afc9efd02f1093ea8e432
3,20201105,56,9507833,124805324,11233.0,53322.0,487415.0,10918.0,25276.0,2877.0,...,152473798,2020-11-05T24:00:00Z,0,0,1124,3735,1154515,116153,1537214,3c8b68743573c3f92cac0382adfa8fc09511b4a9
4,20201104,56,9391680,123650809,10117.0,52049.0,483680.0,10761.0,25041.0,2832.0,...,150936584,2020-11-04T24:00:00Z,0,0,1116,2802,861722,103067,1207099,d3bb88891bd0df62c913c0cc9079fe995cc59ac3

In [59]:
for col in covid.columns:
    print(col)

date
states
positive
negative
pending
hospitalizedCurrently
hospitalizedCumulative
inIcuCurrently
inIcuCumulative
onVentilatorCurrently
onVentilatorCumulative
recovered
dateChecked
death
hospitalized
totalTestResults
lastModified
total
posNeg
deathIncrease
hospitalizedIncrease
negativeIncrease
positiveIncrease
totalTestResultsIncrease
hash

In [60]:
#Step 1: Remove Hash field
covid.drop('hash', axis = 1, inplace=True)

In [61]:
covid.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,totalTestResults,lastModified,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20201108,56,9864069,127671847,23353.0,56768.0,494349.0,11108.0,25819.0,2959.0,...,494349.0,156478414,2020-11-08T24:00:00Z,0,0,462,1576,778663,102588,1086653
1,20201107,56,9761481,126893184,23295.0,55817.0,492773.0,11078.0,25721.0,2943.0,...,492773.0,155391761,2020-11-07T24:00:00Z,0,0,1097,2304,974432,128396,1384557
2,20201106,56,9633085,125918752,11804.0,54824.0,490469.0,11085.0,25498.0,2850.0,...,490469.0,154007204,2020-11-06T24:00:00Z,0,0,1186,3054,1113428,125252,1533406
3,20201105,56,9507833,124805324,11233.0,53322.0,487415.0,10918.0,25276.0,2877.0,...,487415.0,152473798,2020-11-05T24:00:00Z,0,0,1124,3735,1154515,116153,1537214
4,20201104,56,9391680,123650809,10117.0,52049.0,483680.0,10761.0,25041.0,2832.0,...,483680.0,150936584,2020-11-04T24:00:00Z,0,0,1116,2802,861722,103067,1207099

In [68]:
#step 2: Fill missing values from pending field
#step 3: Convert pending from float to int
for col in covid.columns:
    try:
        covid[col] = covid[col].fillna(0.0).astype(int)
    except:
        print("Not a column that can be converted to an int")

Not a column that can be converted to an int
Not a column that can be converted to an int
Not a column that can be converted to an int

In [69]:
type(covid['pending'][0])

numpy.int32

In [70]:
covid.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,totalTestResults,lastModified,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,2020-11-08,56,9864069,127671847,23353,56768,494349,11108,25819,2959,...,494349,156478414,2020-11-08T24:00:00Z,0,0,462,1576,778663,102588,1086653
1,2020-11-07,56,9761481,126893184,23295,55817,492773,11078,25721,2943,...,492773,155391761,2020-11-07T24:00:00Z,0,0,1097,2304,974432,128396,1384557
2,2020-11-06,56,9633085,125918752,11804,54824,490469,11085,25498,2850,...,490469,154007204,2020-11-06T24:00:00Z,0,0,1186,3054,1113428,125252,1533406
3,2020-11-05,56,9507833,124805324,11233,53322,487415,10918,25276,2877,...,487415,152473798,2020-11-05T24:00:00Z,0,0,1124,3735,1154515,116153,1537214
4,2020-11-04,56,9391680,123650809,10117,52049,483680,10761,25041,2832,...,483680,150936584,2020-11-04T24:00:00Z,0,0,1116,2802,861722,103067,1207099

In [71]:
#step 4: format date
covid['date'] = pd.to_datetime(covid['date'], format='%Y%m%d')

In [72]:
covid.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,totalTestResults,lastModified,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,2020-11-08,56,9864069,127671847,23353,56768,494349,11108,25819,2959,...,494349,156478414,2020-11-08T24:00:00Z,0,0,462,1576,778663,102588,1086653
1,2020-11-07,56,9761481,126893184,23295,55817,492773,11078,25721,2943,...,492773,155391761,2020-11-07T24:00:00Z,0,0,1097,2304,974432,128396,1384557
2,2020-11-06,56,9633085,125918752,11804,54824,490469,11085,25498,2850,...,490469,154007204,2020-11-06T24:00:00Z,0,0,1186,3054,1113428,125252,1533406
3,2020-11-05,56,9507833,124805324,11233,53322,487415,10918,25276,2877,...,487415,152473798,2020-11-05T24:00:00Z,0,0,1124,3735,1154515,116153,1537214
4,2020-11-04,56,9391680,123650809,10117,52049,483680,10761,25041,2832,...,483680,150936584,2020-11-04T24:00:00Z,0,0,1116,2802,861722,103067,1207099

In [78]:
#Step 5: Find how many NaN or null values exist and then remove them if they exist
nullList = covid.isnull().sum(axis=1)
for row in nullList:
    print(row)
#There are no null values in the dataframe

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0